//
//  AiGoodbyeIntents.swift
//  AIGoodbye
//
//  Siri + Shortcuts integration: ask the private on-device AI from
//  anywhere on the system, and use it as a building block in automations.
//  Answers are generated by the same engines as the app - Apple
//  Intelligence when available, otherwise a downloaded model - and never
//  leave the device.
//

import AppIntents
import Foundation

// MARK: - Ask intent

struct AskAiGoodbyeIntent: AppIntent {
    static let title: LocalizedStringResource = "Ask AiGoodbye"
    static let description = IntentDescription(
        "Ask the private on-device AI a question. The answer is generated entirely on your device."
    )

    @Parameter(title: "Question", requestValueDialog: "What would you like to ask?")
    var question: String

    static var parameterSummary: some ParameterSummary {
        Summary("Ask AiGoodbye \(\.$question)")
    }

    @MainActor
    func perform() async throws -> some IntentResult & ReturnsValue<String> & ProvidesDialog {
        let answer = try await IntentAnswering.answer(prompt: question)
        return .result(value: answer, dialog: IntentDialog(stringLiteral: String(answer.prefix(900))))
    }
}

// MARK: - Summarize intent (for pipelines: pass any text in, get a summary out)

struct SummarizeWithAiGoodbyeIntent: AppIntent {
    static let title: LocalizedStringResource = "Summarize with AiGoodbye"
    static let description = IntentDescription(
        "Summarize any text privately, on-device. Great after 'Get Text from Input' in a shortcut."
    )

    @Parameter(title: "Text", requestValueDialog: "What text should I summarize?")
    var text: String

    static var parameterSummary: some ParameterSummary {
        Summary("Summarize \(\.$text) with AiGoodbye")
    }

    @MainActor
    func perform() async throws -> some IntentResult & ReturnsValue<String> & ProvidesDialog {
        let prompt = "Summarize the following text concisely, keeping the key points:\n\n\(text.prefix(6000))"
        let answer = try await IntentAnswering.answer(prompt: prompt)
        return .result(value: answer, dialog: IntentDialog(stringLiteral: String(answer.prefix(900))))
    }
}

// MARK: - Shared answering path

enum IntentAnsweringError: Error, CustomLocalizedStringResourceConvertible {
    case noEngine

    var localizedStringResource: LocalizedStringResource {
        switch self {
        case .noEngine:
            return "Open AiGoodbye once to set up an AI model, then try again."
        }
    }
}

@MainActor
enum IntentAnswering {

    /// One-shot answer using the app's engines. Prefers the instantly
    /// available backend so Siri feels fast.
    static func answer(prompt: String) async throws -> String {
        guard let appState = AppState.shared else {
            throw IntentAnsweringError.noEngine
        }
        let engine = appState.engine

        // Choose a backend: Apple Intelligence when available (instant),
        // otherwise an already-downloaded model that fits this device.
        let model: AIModel
        if engine.appleIntelligence.isAvailable {
            model = .appleIntelligence
        } else if engine.selectedModel.backend == .mlx && engine.selectedModel.isDownloaded {
            model = engine.selectedModel
        } else if let downloaded = AIModel.allModels.first(where: { $0.isDownloaded && $0.fitsThisDevice() }) {
            model = downloaded
        } else {
            throw IntentAnsweringError.noEngine
        }

        try await engine.startConversation(model: model, history: [])

        var final = ""
        let stream = engine.respondStream(model: model, prompt: prompt, image: nil)
        for try await snapshot in stream {
            final = snapshot
        }

        // Don't leave the one-shot session behind for the chat UI.
        engine.resetSessions()

        let cleaned = final.trimmingCharacters(in: .whitespacesAndNewlines)
        return cleaned.isEmpty ? L10n.text("No answer was generated. Please try again.") : cleaned
    }
}

// MARK: - App Shortcuts (zero-setup Siri phrases)

struct AiGoodbyeShortcuts: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        AppShortcut(
            intent: AskAiGoodbyeIntent(),
            phrases: [
                "Ask \(.applicationName)",
                "Ask \(.applicationName) a question"
            ],
            shortTitle: "Ask AiGoodbye",
            systemImageName: "bubble.left.and.bubble.right.fill"
        )
        AppShortcut(
            intent: SummarizeWithAiGoodbyeIntent(),
            phrases: [
                "Summarize with \(.applicationName)"
            ],
            shortTitle: "Summarize",
            systemImageName: "doc.plaintext"
        )
    }
}
