//
//  AiGoodbyeIntents.swift
//  AIGoodbye
//
//  Siri + Shortcuts integration: ask the private on-device AI from
//  anywhere on the system, and use it as a building block in automations.
//  Answers are generated by the same engines as the app - Apple
//  Intelligence when available, otherwise a downloaded model - and never
//  leave the device.
//

import AppIntents
import Foundation

// MARK: - Ask intent

struct AskAiGoodbyeIntent: AppIntent {
    static let title: LocalizedStringResource = "Ask AiGoodbye"
    static let description = IntentDescription(
        "Ask the private on-device AI a question. The answer is generated entirely on your device."
    )

    @Parameter(title: "Question", requestValueDialog: "What would you like to ask?")
    var question: String

    static var parameterSummary: some ParameterSummary {
        Summary("Ask AiGoodbye \(\.$question)")
    }

    @MainActor
    func perform() async throws -> some IntentResult & ReturnsValue<String> & ProvidesDialog {
        let answer = try await IntentAnswering.answer(prompt: question)
        return .result(value: answer, dialog: IntentDialog(stringLiteral: String(answer.prefix(900))))
    }
}

// MARK: - Summarize intent (for pipelines: pass any text in, get a summary out)

struct SummarizeWithAiGoodbyeIntent: AppIntent {
    static let title: LocalizedStringResource = "Summarize with AiGoodbye"
    static let description = IntentDescription(
        "Summarize any text privately, on-device. Great after 'Get Text from Input' in a shortcut."
    )

    @Parameter(title: "Text", requestValueDialog: "What text should I summarize?")
    var text: String

    static var parameterSummary: some ParameterSummary {
        Summary("Summarize \(\.$text) with AiGoodbye")
    }

    @MainActor
    func perform() async throws -> some IntentResult & ReturnsValue<String> & ProvidesDialog {
        // Keep well inside the on-device context window; Apple Intelligence
        // throws on oversized prompts.
        let prompt = "Summarize the following text concisely, keeping the key points:\n\n\(text.prefix(3500))"
        let answer = try await IntentAnswering.answer(prompt: prompt)
        return .result(value: answer, dialog: IntentDialog(stringLiteral: String(answer.prefix(900))))
    }
}

// MARK: - Shared answering path

enum IntentAnsweringError: Error, CustomLocalizedStringResourceConvertible {
    case noEngine
    case timedOut
    case locked
    case busy

    var localizedStringResource: LocalizedStringResource {
        switch self {
        case .noEngine:
            return "Open AiGoodbye once to set up an AI model, then try again."
        case .timedOut:
            return "That took too long to answer. Try a shorter question, or ask in the app."
        case .locked:
            return "AiGoodbye is locked. Open the app and unlock it first."
        case .busy:
            return "AiGoodbye is busy with another task. Try again in a moment."
        }
    }
}

@MainActor
enum IntentAnswering {

    /// One-shot answer using the app's engines. Prefers the instantly
    /// available backend so Siri feels fast. Works without a running scene
    /// because the engine lives in EngineHost, not in the view tree.
    static func answer(prompt: String) async throws -> String {
        let engine = EngineHost.shared.engine

        // App Lock has to cover Siri too. Otherwise anyone holding the phone
        // can ask a question and get an answer shaped by the locked user's
        // saved memory facts - which is precisely what the lock exists to
        // prevent.
        guard !AppLock.shared.isLocked else {
            throw IntentAnsweringError.locked
        }

        // Choose a backend. Apple Intelligence is instant and memory-light,
        // so it's strongly preferred here: loading a multi-gigabyte MLX
        // model inside a background Siri process would be jetsam-killed.
        let model: AIModel
        if engine.appleIntelligence.isAvailable {
            model = .appleIntelligence
        } else if let loadedId = engine.mlx.loadedModelId,
                  let loaded = AIModel.model(withId: loadedId) {
            model = loaded   // already resident: cheap to reuse
        } else if AppState.shared != nil,
                  engine.selectedModel.backend == .mlx,
                  engine.selectedModel.isDownloaded,
                  engine.selectedModel.fitsThisDevice() {
            model = engine.selectedModel   // app is running: safe to load
        } else {
            throw IntentAnsweringError.noEngine
        }

        // Take exclusive use of the engine: a Siri answer that tore down a
        // running summary's or translation's session (or had its own torn
        // down) would fail in a way neither side could explain.
        guard engine.claimUtility() else {
            throw IntentAnsweringError.busy
        }
        // Always hand the chat UI a clean slate afterwards: leaving this
        // one-shot session behind would erase the user's conversation
        // memory on their next message.
        defer { engine.releaseUtility() }

        // A base prompt, not the personalized one: a Siri answer must not be
        // shaped by private memory facts.
        try await engine.startCleanSession(model: model)

        // Siri has a limited response budget; don't hang forever.
        return try await withThrowingTaskGroup(of: String.self) { group in
            group.addTask { @MainActor in
                var final = ""
                let stream = engine.respondStream(model: model, prompt: prompt, image: nil)
                for try await snapshot in stream {
                    final = snapshot
                }
                return final
            }
            group.addTask {
                try await Task.sleep(nanoseconds: 25_000_000_000)
                throw IntentAnsweringError.timedOut
            }
            let first = try await group.next() ?? ""
            group.cancelAll()
            let cleaned = first.trimmingCharacters(in: .whitespacesAndNewlines)
            return cleaned.isEmpty ? L10n.text("No answer was generated. Please try again.") : cleaned
        }
    }
}

// MARK: - App Shortcuts (zero-setup Siri phrases)

struct AiGoodbyeShortcuts: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        AppShortcut(
            intent: AskAiGoodbyeIntent(),
            phrases: [
                "Ask \(.applicationName)",
                "Ask \(.applicationName) a question"
            ],
            shortTitle: "Ask AiGoodbye",
            systemImageName: "bubble.left.and.bubble.right.fill"
        )
        AppShortcut(
            intent: SummarizeWithAiGoodbyeIntent(),
            phrases: [
                "Summarize with \(.applicationName)"
            ],
            shortTitle: "Summarize",
            systemImageName: "doc.plaintext"
        )
    }
}
