//
//  TermsView.swift
//  AIGoodbye
//
//  Terms and Conditions acceptance screen (first launch)
//

import SwiftUI

struct TermsView: View {
    @Binding var hasAcceptedTerms: Bool
    @State private var hasScrolledToBottom = false
    @State private var scrollOffset: CGFloat = 0

    var body: some View {
        VStack(spacing: 0) {
            // Header
            VStack(spacing: 12) {
                Image(systemName: "doc.text.fill")
                    .font(.system(size: 50))
                    .foregroundStyle(.blue)

                Text("Terms and Conditions")
                    .font(.title.bold())

                Text("Please read and accept to continue")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
            }
            .padding(.vertical, 24)

            Divider()

            // Scrollable Terms Content
            ScrollViewReader { proxy in
                ScrollView {
                    VStack(alignment: .leading, spacing: 16) {
                        termsContent

                        // Bottom marker for scroll detection
                        Color.clear
                            .frame(height: 1)
                            .id("bottom")
                            .onAppear {
                                hasScrolledToBottom = true
                            }
                    }
                    .padding()
                }
            }

            Divider()

            // Accept Button
            VStack(spacing: 12) {
                if !hasScrolledToBottom {
                    Text("Please scroll to read the full terms")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                Button {
                    withAnimation {
                        hasAcceptedTerms = true
                    }
                } label: {
                    Text("Accept Terms and Conditions")
                        .font(.headline)
                        .frame(maxWidth: .infinity)
                        .padding()
                        .background(hasScrolledToBottom ? Color.blue : Color.gray)
                        .foregroundStyle(.white)
                        .clipShape(RoundedRectangle(cornerRadius: 12))
                }
                .disabled(!hasScrolledToBottom)

                Text("Last updated: January 1, 2026")
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
            }
            .padding()
        }
    }

    private var termsContent: some View {
        VStack(alignment: .leading, spacing: 20) {
            Text("Effective Date: January 1, 2026")
                .font(.subheadline)
                .foregroundStyle(.secondary)

            Group {
                sectionTitle("Welcome to AiGoodbye!")

                Text("""
                These Terms and Conditions ("Terms") constitute a legally binding agreement between you and AiGoodbye regarding your use of our application and services. By accessing or using AiGoodbye, you agree to comply with and be bound by these Terms.
                """)

                sectionTitle("Acceptance of Terms")

                Text("""
                By using AiGoodbye, you confirm that you are of legal age and capacity to enter into these Terms. If you do not agree to these Terms, you must not use our app.
                """)

                sectionTitle("AI Model Limitations and Disclaimers")

                Text("You acknowledge and agree that:")
                    .fontWeight(.medium)

                bulletPoints([
                    "The AI models in AiGoodbye may generate content that is incorrect, incomplete, misleading, or inappropriate.",
                    "You should not rely on AI-generated content for medical, legal, financial, or other professional advice.",
                    "The AI models may occasionally produce biased, offensive, or harmful content despite our best efforts to prevent such outputs.",
                    "You are solely responsible for verifying any information or content generated by the AI models before acting upon it.",
                    "AiGoodbye is not responsible for any decisions, actions, or consequences resulting from your use of AI-generated content.",
                    "The AI models' responses are generated through probabilistic methods and may not reflect current or accurate information.",
                    "Any code, scripts, or technical solutions generated by the AI should be thoroughly reviewed and tested before implementation."
                ])
            }

            Group {
                sectionTitle("Data and Privacy")

                Text("Regarding data privacy and processing:")
                    .fontWeight(.medium)

                bulletPoints([
                    "All AI processing occurs entirely on your device - no data is sent to external servers",
                    "Your conversations, images, and documents never leave your device",
                    "You are responsible for the security of your device and any data you input into the app",
                    "You are responsible for ensuring you have the right to use any content you input into the app",
                    "You are responsible for any consequences of sharing AI-generated content with third parties"
                ])

                sectionTitle("On-Device Processing")

                Text("Regarding on-device AI:")
                    .fontWeight(.medium)

                bulletPoints([
                    "AiGoodbye runs AI models locally on your device using Apple's MLX framework",
                    "No internet connection is required for AI features after the initial model download",
                    "Your privacy is protected as all processing happens on-device",
                    "Model performance depends on your device's capabilities"
                ])
            }

            Group {
                sectionTitle("Prohibited Uses")

                Text("You agree not to use AiGoodbye:")
                    .fontWeight(.medium)

                bulletPoints([
                    "For any unlawful purpose or to generate content that promotes illegal activities",
                    "To generate content that is discriminatory, hateful, or promotes harm against individuals or groups",
                    "To create misleading or fraudulent content",
                    "To generate spam, malware, or other malicious content",
                    "In any way that could damage, disable, or impair the app's functionality",
                    "To attempt to reverse engineer or extract the AI models",
                    "To generate content that infringes on intellectual property rights",
                    "To attempt to identify or reverse engineer the training data or architecture of the AI models",
                    "For automated or systematic extraction of content from the app"
                ])

                sectionTitle("Disclaimer of Warranties")

                Text("""
                AIGOODBYE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED. We specifically disclaim any implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
                """)
                .fontWeight(.medium)
            }

            Group {
                sectionTitle("Limitation of Liability")

                Text("TO THE MAXIMUM EXTENT PERMITTED BY LAW:")
                    .fontWeight(.bold)

                bulletPoints([
                    "AIGOODBYE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES",
                    "OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING FROM OR RELATED TO YOUR USE OF THE APP SHALL NOT EXCEED THE AMOUNT YOU PAID FOR THE APP",
                    "WE ARE NOT LIABLE FOR ANY ACTIONS YOU TAKE OR REFRAIN FROM TAKING BASED ON AI-GENERATED CONTENT",
                    "WE ARE NOT LIABLE FOR ANY LOSS OF DATA, PROFIT, GOODWILL, OR BUSINESS OPPORTUNITY",
                    "WE ARE NOT LIABLE FOR ANY INTERRUPTION OF BUSINESS OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES",
                    "WE ARE NOT LIABLE FOR ANY ACTIONS, POLICIES, OR DATA PRACTICES OF THIRD-PARTY SERVICES",
                    "THESE LIMITATIONS APPLY EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES"
                ])

                sectionTitle("Export Control")

                Text("You agree to comply with all applicable export control laws and regulations in your use of the app and its AI capabilities.")

                sectionTitle("Indemnification")

                Text("""
                You agree to indemnify, defend, and hold harmless AiGoodbye and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including reasonable attorneys' fees, arising out of or in any way connected with your use of the app or violation of these Terms.
                """)
            }

            Group {
                sectionTitle("Changes to Terms")

                Text("""
                We reserve the right to modify these Terms at any time. We will notify you of material changes through the app or website. Your continued use after such modifications constitutes acceptance of the updated Terms.
                """)

                sectionTitle("Governing Law and Jurisdiction")

                Text("""
                These Terms are governed by USA law. Any disputes shall be subject to the exclusive jurisdiction of USA courts. You agree to submit to the personal jurisdiction of such courts.
                """)

                sectionTitle("Severability")

                Text("If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.")

                sectionTitle("Contact Us")

                Text("If you have any questions about these Terms, please contact us at:")

                if let emailURL = AppConfig.Contact.supportEmailURL {
                    Link(AppConfig.Contact.supportEmail, destination: emailURL)
                        .foregroundStyle(.blue)
                }
            }
        }
        .font(.body)
    }

    private func sectionTitle(_ text: String) -> some View {
        Text(text)
            .font(.headline)
            .padding(.top, 8)
    }

    private func bulletPoints(_ points: [String]) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            ForEach(points, id: \.self) { point in
                HStack(alignment: .top, spacing: 8) {
                    Text("•")
                    Text(point)
                }
            }
        }
        .padding(.leading, 8)
    }
}

#Preview {
    TermsView(hasAcceptedTerms: .constant(false))
}
